import Cryptarchia.Prob.CertE
import Cryptarchia.Prob.FinalTSI

/-!
# E20D11: the band family

Generated by `tools/certgen/emitE.py`.
-/

namespace Cryptarchia.Prob.Certs.E20D11

open Cryptarchia Cryptarchia.Prob

set_option maxRecDepth 100000
set_option maxHeartbeats 0


/-- Member 0: honest exponent in [0.024220, 0.025995], adversary ≤ 0.006499. -/
noncomputable def f0 : Band where
  hhi := (2566063419223 / 100000000000000 : ℝ)
  hlo := (2391163478071 / 100000000000000 : ℝ)
  amax := (6477592332713 / 1000000000000000 : ℝ)
  hahi := (831095636481 / 5000000000000000 : ℝ)
  slo := (93753032953 / 4000000000000 : ℝ)
  hnlo := (2375674495859 / 100000000000000 : ℝ)
  elo := (9680279926023 / 10000000000000 : ℝ)
  alo := (6477592332713 / 1000000000000000 : ℝ)
  halo := (1548898221181 / 10000000000000000 : ℝ)

/-- Member 1: honest exponent in [0.025995, 0.027899], adversary ≤ 0.006975. -/
noncomputable def f1 : Band where
  hhi := (2751464166377 / 100000000000000 : ℝ)
  hlo := (1281896180637 / 50000000000000 : ℝ)
  amax := (6950500080849 / 1000000000000000 : ℝ)
  hahi := (956202595543 / 5000000000000000 : ℝ)
  slo := (1254716687077 / 50000000000000 : ℝ)
  hnlo := (2545972722259 / 100000000000000 : ℝ)
  elo := (301789405867 / 312500000000 : ℝ)
  alo := (6950500080849 / 1000000000000000 : ℝ)
  halo := (1781963901431 / 10000000000000000 : ℝ)

/-- Member 2: honest exponent in [0.027899, 0.029943], adversary ≤ 0.007486. -/
noncomputable def f2 : Band where
  hhi := (590011836441 / 20000000000000 : ℝ)
  hlo := (2748660926139 / 100000000000000 : ℝ)
  amax := (74578039207 / 10000000000000 : ℝ)
  hahi := (440019258707 / 2000000000000000 : ℝ)
  slo := (2686253569339 / 100000000000000 : ℝ)
  hnlo := (2728161951907 / 100000000000000 : ℝ)
  elo := (4816308069433 / 5000000000000 : ℝ)
  alo := (74578039207 / 10000000000000 : ℝ)
  halo := (2049897423163 / 10000000000000000 : ℝ)

/-- Member 3: honest exponent in [0.029943, 0.032137], adversary ≤ 0.008034. -/
noncomputable def f3 : Band where
  hhi := (1581378681417 / 50000000000000 : ℝ)
  hlo := (2946599449387 / 100000000000000 : ℝ)
  amax := (500124125721 / 62500000000000 : ℝ)
  hahi := (2530834017529 / 10000000000000000 : ℝ)
  slo := (2874969861383 / 100000000000000 : ℝ)
  hnlo := (2923020801811 / 100000000000000 : ℝ)
  elo := (4803117618809 / 5000000000000 : ℝ)
  alo := (500124125721 / 62500000000000 : ℝ)
  halo := (2357864757559 / 10000000000000000 : ℝ)

/-- Member 4: honest exponent in [0.032137, 0.034491], adversary ≤ 0.008623. -/
noncomputable def f4 : Band where
  hhi := (3390525721761 / 100000000000000 : ℝ)
  hlo := (3158487918651 / 100000000000000 : ℝ)
  amax := (1717140934467 / 200000000000000 : ℝ)
  hahi := (29110052531 / 100000000000000 : ℝ)
  slo := (384536903987 / 12500000000000 : ℝ)
  hnlo := (313137007417 / 10000000000000 : ℝ)
  elo := (9578001386353 / 10000000000000 : ℝ)
  alo := (1717140934467 / 200000000000000 : ℝ)
  halo := (2711784448067 / 10000000000000000 : ℝ)

/-- Member 5: honest exponent in [0.034491, 0.037018], adversary ≤ 0.009254. -/
noncomputable def f5 : Band where
  hhi := (1817196215997 / 50000000000000 : ℝ)
  hlo := (1692628878901 / 50000000000000 : ℝ)
  amax := (575737902171 / 62500000000000 : ℝ)
  hahi := (167396597957 / 500000000000000 : ℝ)
  slo := (3290971337677 / 100000000000000 : ℝ)
  hnlo := (670814683721 / 20000000000000 : ℝ)
  elo := (2386947656103 / 2500000000000 : ℝ)
  alo := (575737902171 / 62500000000000 : ℝ)
  halo := (389804239957 / 1250000000000000 : ℝ)

/-- The weakest band: weaker than every member. -/
noncomputable def B : Band where
  hhi := (1817196215997 / 50000000000000 : ℝ)
  hlo := (2391163478071 / 100000000000000 : ℝ)
  amax := (575737902171 / 62500000000000 : ℝ)
  hahi := (167396597957 / 500000000000000 : ℝ)
  slo := (93753032953 / 4000000000000 : ℝ)
  hnlo := (2375674495859 / 100000000000000 : ℝ)
  elo := (2386947656103 / 2500000000000 : ℝ)
  alo := (6477592332713 / 1000000000000000 : ℝ)
  halo := (1548898221181 / 10000000000000000 : ℝ)

noncomputable def fam : Fin 6 → Band := fun k =>
  match k.val with
  | 0 => f0
  | 1 => f1
  | 2 => f2
  | 3 => f3
  | 4 => f4
  | _ => f5

theorem weak0 : B.Weaker f0 :=
  ⟨by norm_num [B, f0], by norm_num [B, f0], by norm_num [B, f0], by norm_num [B, f0], by norm_num [B, f0], by norm_num [B, f0], by norm_num [B, f0], by norm_num [B, f0], by norm_num [B, f0]⟩

theorem prod0 : f0.Prod :=
  ⟨by norm_num [f0], by norm_num [f0], by norm_num [f0], by norm_num [f0], by norm_num [f0]⟩

theorem patm0 : (409857059673 / 25000000000000 : ℝ) ≤ f0.slo * f0.elo ^ 11 := by norm_num [f0]

theorem elo0 : 0 ≤ f0.elo := by norm_num [f0]

theorem weak1 : B.Weaker f1 :=
  ⟨by norm_num [B, f1], by norm_num [B, f1], by norm_num [B, f1], by norm_num [B, f1], by norm_num [B, f1], by norm_num [B, f1], by norm_num [B, f1], by norm_num [B, f1], by norm_num [B, f1]⟩

theorem prod1 : f1.Prod :=
  ⟨by norm_num [f1], by norm_num [f1], by norm_num [f1], by norm_num [f1], by norm_num [f1]⟩

theorem patm1 : (341978905069 / 20000000000000 : ℝ) ≤ f1.slo * f1.elo ^ 11 := by norm_num [f1]

theorem elo1 : 0 ≤ f1.elo := by norm_num [f1]

theorem weak2 : B.Weaker f2 :=
  ⟨by norm_num [B, f2], by norm_num [B, f2], by norm_num [B, f2], by norm_num [B, f2], by norm_num [B, f2], by norm_num [B, f2], by norm_num [B, f2], by norm_num [B, f2], by norm_num [B, f2]⟩

theorem prod2 : f2.Prod :=
  ⟨by norm_num [f2], by norm_num [f2], by norm_num [f2], by norm_num [f2], by norm_num [f2]⟩

theorem patm2 : (1779646721379 / 100000000000000 : ℝ) ≤ f2.slo * f2.elo ^ 11 := by norm_num [f2]

theorem elo2 : 0 ≤ f2.elo := by norm_num [f2]

theorem weak3 : B.Weaker f3 :=
  ⟨by norm_num [B, f3], by norm_num [B, f3], by norm_num [B, f3], by norm_num [B, f3], by norm_num [B, f3], by norm_num [B, f3], by norm_num [B, f3], by norm_num [B, f3], by norm_num [B, f3]⟩

theorem prod3 : f3.Prod :=
  ⟨by norm_num [f3], by norm_num [f3], by norm_num [f3], by norm_num [f3], by norm_num [f3]⟩

theorem patm3 : (924035576679 / 50000000000000 : ℝ) ≤ f3.slo * f3.elo ^ 11 := by norm_num [f3]

theorem elo3 : 0 ≤ f3.elo := by norm_num [f3]

theorem weak4 : B.Weaker f4 :=
  ⟨by norm_num [B, f4], by norm_num [B, f4], by norm_num [B, f4], by norm_num [B, f4], by norm_num [B, f4], by norm_num [B, f4], by norm_num [B, f4], by norm_num [B, f4], by norm_num [B, f4]⟩

theorem prod4 : f4.Prod :=
  ⟨by norm_num [f4], by norm_num [f4], by norm_num [f4], by norm_num [f4], by norm_num [f4]⟩

theorem patm4 : (1914484539767 / 100000000000000 : ℝ) ≤ f4.slo * f4.elo ^ 11 := by norm_num [f4]

theorem elo4 : 0 ≤ f4.elo := by norm_num [f4]

theorem weak5 : B.Weaker f5 :=
  ⟨by norm_num [B, f5], by norm_num [B, f5], by norm_num [B, f5], by norm_num [B, f5], by norm_num [B, f5], by norm_num [B, f5], by norm_num [B, f5], by norm_num [B, f5], by norm_num [B, f5]⟩

theorem prod5 : f5.Prod :=
  ⟨by norm_num [f5], by norm_num [f5], by norm_num [f5], by norm_num [f5], by norm_num [f5]⟩

theorem patm5 : (1978134664777 / 100000000000000 : ℝ) ≤ f5.slo * f5.elo ^ 11 := by norm_num [f5]

theorem elo5 : 0 ≤ f5.elo := by norm_num [f5]

end Cryptarchia.Prob.Certs.E20D11
