import Cryptarchia.Prob.CertE
import Cryptarchia.Prob.FinalTSI

/-!
# E20D11: the band family

Generated by `tools/certgen/emitE.py`.
-/

namespace Cryptarchia.Prob.Certs.E20D11

open Cryptarchia Cryptarchia.Prob

set_option maxRecDepth 100000
set_option maxHeartbeats 0


/-- Member 0: honest exponent in [0.024220, 0.026468], adversary ≤ 0.006617. -/
noncomputable def f0 : Band where
  hhi := (1306084837083 / 50000000000000 : ℝ)
  hlo := (59776967911 / 2500000000000 : ℝ)
  amax := (3297567372929 / 500000000000000 : ℝ)
  hahi := (1722761098017 / 10000000000000000 : ℝ)
  slo := (117119877123 / 5000000000000 : ℝ)
  hnlo := (2375309230117 / 100000000000000 : ℝ)
  elo := (4837277223111 / 5000000000000 : ℝ)
  alo := (3297567372929 / 500000000000000 : ℝ)
  halo := (1576948632287 / 10000000000000000 : ℝ)

/-- Member 1: honest exponent in [0.026468, 0.028924], adversary ≤ 0.007231. -/
noncomputable def f1 : Band where
  hhi := (1425558926703 / 50000000000000 : ℝ)
  hlo := (2609662873009 / 100000000000000 : ℝ)
  amax := (7204965920809 / 1000000000000000 : ℝ)
  hahi := (2054220697001 / 10000000000000000 : ℝ)
  slo := (2551758460643 / 100000000000000 : ℝ)
  hnlo := (161928771309 / 6250000000000 : ℝ)
  elo := (2411223194037 / 2500000000000 : ℝ)
  alo := (7204965920809 / 1000000000000000 : ℝ)
  halo := (1880253206483 / 10000000000000000 : ℝ)

/-- Member 2: honest exponent in [0.028924, 0.031608], adversary ≤ 0.007902. -/
noncomputable def f2 : Band where
  hhi := (1555788766343 / 50000000000000 : ℝ)
  hlo := (1423926541159 / 50000000000000 : ℝ)
  amax := (3935481628509 / 500000000000000 : ℝ)
  hahi := (1224555621557 / 5000000000000000 : ℝ)
  slo := (2779003893463 / 100000000000000 : ℝ)
  hnlo := (565087547069 / 20000000000000 : ℝ)
  elo := (2403145431351 / 2500000000000 : ℝ)
  alo := (3935481628509 / 500000000000000 : ℝ)
  halo := (2241534697231 / 10000000000000000 : ℝ)

/-- Member 3: honest exponent in [0.031608, 0.034542], adversary ≤ 0.008635. -/
noncomputable def f3 : Band where
  hhi := (169770957887 / 5000000000000 : ℝ)
  hlo := (621465282469 / 20000000000000 : ℝ)
  amax := (1719651316169 / 200000000000000 : ℝ)
  hahi := (2919468511777 / 10000000000000000 : ℝ)
  slo := (756374371987 / 25000000000000 : ℝ)
  hnlo := (3080608822571 / 100000000000000 : ℝ)
  elo := (9577394986929 / 10000000000000 : ℝ)
  alo := (1719651316169 / 200000000000000 : ℝ)
  halo := (2671758977377 / 10000000000000000 : ℝ)

/-- Member 4: honest exponent in [0.034542, 0.037747], adversary ≤ 0.009437. -/
noncomputable def f4 : Band where
  hhi := (115770725433 / 3125000000000 : ℝ)
  hlo := (338988483663 / 10000000000000 : ℝ)
  amax := (587027243583 / 62500000000000 : ℝ)
  hahi := (1739790587867 / 5000000000000000 : ℝ)
  slo := (3292673161331 / 100000000000000 : ℝ)
  hnlo := (1679022780301 / 50000000000000 : ℝ)
  elo := (596193056301 / 625000000000 : ℝ)
  alo := (587027243583 / 62500000000000 : ℝ)
  halo := (3183927602737 / 10000000000000000 : ℝ)

/-- Member 5: honest exponent in [0.037747, 0.041250], adversary ≤ 0.010313. -/
noncomputable def f5 : Band where
  hhi := (2020744926487 / 50000000000000 : ℝ)
  hlo := (1848729990927 / 50000000000000 : ℝ)
  amax := (102595910551 / 10000000000000 : ℝ)
  hahi := (829280662897 / 2000000000000000 : ℝ)
  slo := (3582031077309 / 100000000000000 : ℝ)
  hnlo := (3659525554497 / 100000000000000 : ℝ)
  elo := (4748700753733 / 5000000000000 : ℝ)
  alo := (102595910551 / 10000000000000 : ℝ)
  halo := (3793442735641 / 10000000000000000 : ℝ)

/-- The weakest band: weaker than every member. -/
noncomputable def B : Band where
  hhi := (2020744926487 / 50000000000000 : ℝ)
  hlo := (59776967911 / 2500000000000 : ℝ)
  amax := (102595910551 / 10000000000000 : ℝ)
  hahi := (829280662897 / 2000000000000000 : ℝ)
  slo := (117119877123 / 5000000000000 : ℝ)
  hnlo := (2375309230117 / 100000000000000 : ℝ)
  elo := (4748700753733 / 5000000000000 : ℝ)
  alo := (3297567372929 / 500000000000000 : ℝ)
  halo := (1576948632287 / 10000000000000000 : ℝ)

noncomputable def fam : Fin 6 → Band := fun k =>
  match k.val with
  | 0 => f0
  | 1 => f1
  | 2 => f2
  | 3 => f3
  | 4 => f4
  | _ => f5

theorem weak0 : B.Weaker f0 :=
  ⟨by norm_num [B, f0], by norm_num [B, f0], by norm_num [B, f0], by norm_num [B, f0], by norm_num [B, f0], by norm_num [B, f0], by norm_num [B, f0], by norm_num [B, f0], by norm_num [B, f0]⟩

theorem prod0 : f0.Prod :=
  ⟨by norm_num [f0], by norm_num [f0], by norm_num [f0], by norm_num [f0], by norm_num [f0]⟩

theorem patm0 : (325560197427 / 20000000000000 : ℝ) ≤ f0.slo * f0.elo ^ 11 := by norm_num [f0]

theorem elo0 : 0 ≤ f0.elo := by norm_num [f0]

theorem weak1 : B.Weaker f1 :=
  ⟨by norm_num [B, f1], by norm_num [B, f1], by norm_num [B, f1], by norm_num [B, f1], by norm_num [B, f1], by norm_num [B, f1], by norm_num [B, f1], by norm_num [B, f1], by norm_num [B, f1]⟩

theorem prod1 : f1.Prod :=
  ⟨by norm_num [f1], by norm_num [f1], by norm_num [f1], by norm_num [f1], by norm_num [f1]⟩

theorem patm1 : (53574857899 / 3125000000000 : ℝ) ≤ f1.slo * f1.elo ^ 11 := by norm_num [f1]

theorem elo1 : 0 ≤ f1.elo := by norm_num [f1]

theorem weak2 : B.Weaker f2 :=
  ⟨by norm_num [B, f2], by norm_num [B, f2], by norm_num [B, f2], by norm_num [B, f2], by norm_num [B, f2], by norm_num [B, f2], by norm_num [B, f2], by norm_num [B, f2], by norm_num [B, f2]⟩

theorem prod2 : f2.Prod :=
  ⟨by norm_num [f2], by norm_num [f2], by norm_num [f2], by norm_num [f2], by norm_num [f2]⟩

theorem patm2 : (224926002611 / 12500000000000 : ℝ) ≤ f2.slo * f2.elo ^ 11 := by norm_num [f2]

theorem elo2 : 0 ≤ f2.elo := by norm_num [f2]

theorem weak3 : B.Weaker f3 :=
  ⟨by norm_num [B, f3], by norm_num [B, f3], by norm_num [B, f3], by norm_num [B, f3], by norm_num [B, f3], by norm_num [B, f3], by norm_num [B, f3], by norm_num [B, f3], by norm_num [B, f3]⟩

theorem prod3 : f3.Prod :=
  ⟨by norm_num [f3], by norm_num [f3], by norm_num [f3], by norm_num [f3], by norm_num [f3]⟩

theorem patm3 : (1881560482733 / 100000000000000 : ℝ) ≤ f3.slo * f3.elo ^ 11 := by norm_num [f3]

theorem elo3 : 0 ≤ f3.elo := by norm_num [f3]

theorem weak4 : B.Weaker f4 :=
  ⟨by norm_num [B, f4], by norm_num [B, f4], by norm_num [B, f4], by norm_num [B, f4], by norm_num [B, f4], by norm_num [B, f4], by norm_num [B, f4], by norm_num [B, f4], by norm_num [B, f4]⟩

theorem prod4 : f4.Prod :=
  ⟨by norm_num [f4], by norm_num [f4], by norm_num [f4], by norm_num [f4], by norm_num [f4]⟩

theorem patm4 : (979703110839 / 50000000000000 : ℝ) ≤ f4.slo * f4.elo ^ 11 := by norm_num [f4]

theorem elo4 : 0 ≤ f4.elo := by norm_num [f4]

theorem weak5 : B.Weaker f5 :=
  ⟨by norm_num [B, f5], by norm_num [B, f5], by norm_num [B, f5], by norm_num [B, f5], by norm_num [B, f5], by norm_num [B, f5], by norm_num [B, f5], by norm_num [B, f5], by norm_num [B, f5]⟩

theorem prod5 : f5.Prod :=
  ⟨by norm_num [f5], by norm_num [f5], by norm_num [f5], by norm_num [f5], by norm_num [f5]⟩

theorem patm5 : (1015668857477 / 50000000000000 : ℝ) ≤ f5.slo * f5.elo ^ 11 := by norm_num [f5]

theorem elo5 : 0 ≤ f5.elo := by norm_num [f5]

end Cryptarchia.Prob.Certs.E20D11
