import Cryptarchia.Prob.CertE
import Cryptarchia.Prob.FinalTSI

/-!
# E10D11: the band family

Generated by `tools/certgen/emitE.py`.
-/

namespace Cryptarchia.Prob.Certs.E10D11

open Cryptarchia Cryptarchia.Prob

set_option maxRecDepth 100000
set_option maxHeartbeats 0


/-- Member 0: honest exponent in [0.025826, 0.027744], adversary ≤ 0.003083. -/
noncomputable def f0 : Band where
  hhi := (1368212387243 / 50000000000000 : ℝ)
  hlo := (1273704701191 / 50000000000000 : ℝ)
  amax := (3077963535521 / 1000000000000000 : ℝ)
  hahi := (1684523134713 / 20000000000000000 : ℝ)
  slo := (500657106471 / 20000000000000 : ℝ)
  hnlo := (2539568569131 / 100000000000000 : ℝ)
  elo := (9696420148763 / 10000000000000 : ℝ)
  alo := (3077963535521 / 1000000000000000 : ℝ)
  halo := (313633330023 / 4000000000000000 : ℝ)

/-- Member 1: honest exponent in [0.027744, 0.029805], adversary ≤ 0.003312. -/
noncomputable def f1 : Band where
  hhi := (2936686307477 / 100000000000000 : ℝ)
  hlo := (1366830521577 / 50000000000000 : ℝ)
  amax := (3306208090397 / 1000000000000000 : ℝ)
  hahi := (9709296028739 / 100000000000000000 : ℝ)
  slo := (2682919256417 / 100000000000000 : ℝ)
  hnlo := (170288936931 / 6250000000000 : ℝ)
  elo := (9674240217951 / 10000000000000 : ℝ)
  alo := (3306208090397 / 1000000000000000 : ℝ)
  halo := (4519026128639 / 50000000000000000 : ℝ)

/-- Member 2: honest exponent in [0.029805, 0.032019], adversary ≤ 0.003558. -/
noncomputable def f2 : Band where
  hhi := (3151368382397 / 100000000000000 : ℝ)
  hlo := (293326569331 / 10000000000000 : ℝ)
  amax := (355134786263 / 100000000000000 : ℝ)
  hahi := (1119160536919 / 10000000000000000 : ℝ)
  slo := (2874929028027 / 100000000000000 : ℝ)
  hnlo := (2922848646459 / 100000000000000 : ℝ)
  elo := (965046884367 / 1000000000000 : ℝ)
  alo := (355134786263 / 100000000000000 : ℝ)
  halo := (520852342523 / 5000000000000000 : ℝ)

/-- Member 3: honest exponent in [0.032019, 0.034397], adversary ≤ 0.003822. -/
noncomputable def f3 : Band where
  hhi := (676294746469 / 20000000000000 : ℝ)
  hlo := (3147135290711 / 100000000000000 : ℝ)
  amax := (381462884401 / 100000000000000 : ℝ)
  hahi := (1289906723467 / 10000000000000000 : ℝ)
  slo := (385010788507 / 12500000000000 : ℝ)
  hnlo := (627026027531 / 20000000000000 : ℝ)
  elo := (1203124530631 / 1250000000000 : ℝ)
  alo := (381462884401 / 100000000000000 : ℝ)
  halo := (600257652797 / 5000000000000000 : ℝ)

/-- Member 4: honest exponent in [0.034397, 0.036952], adversary ≤ 0.004106. -/
noncomputable def f4 : Band where
  hhi := (725613884337 / 20000000000000 : ℝ)
  hlo := (337623588817 / 10000000000000 : ℝ)
  amax := (512173525419 / 125000000000000 : ℝ)
  hahi := (185820110617 / 1250000000000000 : ℝ)
  slo := (412399672003 / 12500000000000 : ℝ)
  hnlo := (336240213907 / 10000000000000 : ℝ)
  elo := (4798852868341 / 5000000000000 : ℝ)
  alo := (512173525419 / 125000000000000 : ℝ)
  halo := (172921863749 / 1250000000000000 : ℝ)

/-- Member 5: honest exponent in [0.036952, 0.039697], adversary ≤ 0.004411. -/
noncomputable def f5 : Band where
  hhi := (973072538389 / 25000000000000 : ℝ)
  hlo := (905397320019 / 25000000000000 : ℝ)
  amax := (2200530424389 / 500000000000000 : ℝ)
  hahi := (171302058069 / 1000000000000000 : ℝ)
  slo := (1766551263189 / 50000000000000 : ℝ)
  hnlo := (721130089057 / 20000000000000 : ℝ)
  elo := (9568473396737 / 10000000000000 : ℝ)
  alo := (2200530424389 / 500000000000000 : ℝ)
  halo := (1593883479089 / 10000000000000000 : ℝ)

/-- The weakest band: weaker than every member. -/
noncomputable def B : Band where
  hhi := (973072538389 / 25000000000000 : ℝ)
  hlo := (1273704701191 / 50000000000000 : ℝ)
  amax := (2200530424389 / 500000000000000 : ℝ)
  hahi := (171302058069 / 1000000000000000 : ℝ)
  slo := (500657106471 / 20000000000000 : ℝ)
  hnlo := (2539568569131 / 100000000000000 : ℝ)
  elo := (9568473396737 / 10000000000000 : ℝ)
  alo := (3077963535521 / 1000000000000000 : ℝ)
  halo := (313633330023 / 4000000000000000 : ℝ)

noncomputable def fam : Fin 6 → Band := fun k =>
  match k.val with
  | 0 => f0
  | 1 => f1
  | 2 => f2
  | 3 => f3
  | 4 => f4
  | _ => f5

theorem weak0 : B.Weaker f0 :=
  ⟨by norm_num [B, f0], by norm_num [B, f0], by norm_num [B, f0], by norm_num [B, f0], by norm_num [B, f0], by norm_num [B, f0], by norm_num [B, f0], by norm_num [B, f0], by norm_num [B, f0]⟩

theorem prod0 : f0.Prod :=
  ⟨by norm_num [f0], by norm_num [f0], by norm_num [f0], by norm_num [f0], by norm_num [f0]⟩

theorem patm0 : (1783347872923 / 100000000000000 : ℝ) ≤ f0.slo * f0.elo ^ 11 := by norm_num [f0]

theorem elo0 : 0 ≤ f0.elo := by norm_num [f0]

theorem weak1 : B.Weaker f1 :=
  ⟨by norm_num [B, f1], by norm_num [B, f1], by norm_num [B, f1], by norm_num [B, f1], by norm_num [B, f1], by norm_num [B, f1], by norm_num [B, f1], by norm_num [B, f1], by norm_num [B, f1]⟩

theorem prod1 : f1.Prod :=
  ⟨by norm_num [f1], by norm_num [f1], by norm_num [f1], by norm_num [f1], by norm_num [f1]⟩

theorem patm1 : (465943382829 / 25000000000000 : ℝ) ≤ f1.slo * f1.elo ^ 11 := by norm_num [f1]

theorem elo1 : 0 ≤ f1.elo := by norm_num [f1]

theorem weak2 : B.Weaker f2 :=
  ⟨by norm_num [B, f2], by norm_num [B, f2], by norm_num [B, f2], by norm_num [B, f2], by norm_num [B, f2], by norm_num [B, f2], by norm_num [B, f2], by norm_num [B, f2], by norm_num [B, f2]⟩

theorem prod2 : f2.Prod :=
  ⟨by norm_num [f2], by norm_num [f2], by norm_num [f2], by norm_num [f2], by norm_num [f2]⟩

theorem patm2 : (485959055323 / 25000000000000 : ℝ) ≤ f2.slo * f2.elo ^ 11 := by norm_num [f2]

theorem elo2 : 0 ≤ f2.elo := by norm_num [f2]

theorem weak3 : B.Weaker f3 :=
  ⟨by norm_num [B, f3], by norm_num [B, f3], by norm_num [B, f3], by norm_num [B, f3], by norm_num [B, f3], by norm_num [B, f3], by norm_num [B, f3], by norm_num [B, f3], by norm_num [B, f3]⟩

theorem prod3 : f3.Prod :=
  ⟨by norm_num [f3], by norm_num [f3], by norm_num [f3], by norm_num [f3], by norm_num [f3]⟩

theorem patm3 : (1011437721947 / 50000000000000 : ℝ) ≤ f3.slo * f3.elo ^ 11 := by norm_num [f3]

theorem elo3 : 0 ≤ f3.elo := by norm_num [f3]

theorem weak4 : B.Weaker f4 :=
  ⟨by norm_num [B, f4], by norm_num [B, f4], by norm_num [B, f4], by norm_num [B, f4], by norm_num [B, f4], by norm_num [B, f4], by norm_num [B, f4], by norm_num [B, f4], by norm_num [B, f4]⟩

theorem prod4 : f4.Prod :=
  ⟨by norm_num [f4], by norm_num [f4], by norm_num [f4], by norm_num [f4], by norm_num [f4]⟩

theorem patm4 : (65629644937 / 3125000000000 : ℝ) ≤ f4.slo * f4.elo ^ 11 := by norm_num [f4]

theorem elo4 : 0 ≤ f4.elo := by norm_num [f4]

theorem weak5 : B.Weaker f5 :=
  ⟨by norm_num [B, f5], by norm_num [B, f5], by norm_num [B, f5], by norm_num [B, f5], by norm_num [B, f5], by norm_num [B, f5], by norm_num [B, f5], by norm_num [B, f5], by norm_num [B, f5]⟩

theorem prod5 : f5.Prod :=
  ⟨by norm_num [f5], by norm_num [f5], by norm_num [f5], by norm_num [f5], by norm_num [f5]⟩

theorem patm5 : (2174830582507 / 100000000000000 : ℝ) ≤ f5.slo * f5.elo ^ 11 := by norm_num [f5]

theorem elo5 : 0 ≤ f5.elo := by norm_num [f5]

end Cryptarchia.Prob.Certs.E10D11
