import Cryptarchia.Prob.Certs.G30D11.G30D11M0
import Cryptarchia.Prob.Certs.G30D11.G30D11M1
import Cryptarchia.Prob.Certs.G30D11.G30D11M2
import Cryptarchia.Prob.Certs.G30D11.G30D11M3
import Cryptarchia.Prob.Certs.G30D11.G30D11M4
import Cryptarchia.Prob.Certs.G30D11.G30D11M5

/-!
# First-epoch finality from stake fractions: β ≤ 0.3, Δ = 11

Generated by `tools/certgen/emit_gen.py`. The genesis state's honest
exponent `λ·H/D` lies in one of 6 ranges covering `[(1-β)λ, λ]`; each range has
its own certificate (`G30D11Mk.certified`). The worst is `10^-10`.
-/

namespace Cryptarchia.Prob.Certs.G30D11

open Cryptarchia Cryptarchia.Prob

set_option maxRecDepth 100000
set_option maxHeartbeats 0
noncomputable def m0 : Member := ⟨(237310861729 / 10000000000000 : ℝ), (239005939313 / 10000000000000 : ℝ), (25426163757 / 2500000000000 : ℝ), G30D11M0.B⟩
noncomputable def m1 : Member := ⟨(239005939313 / 10000000000000 : ℝ), (242396094481 / 10000000000000 : ℝ), (25002394361 / 2500000000000 : ℝ), G30D11M1.B⟩
noncomputable def m2 : Member := ⟨(242396094481 / 10000000000000 : ℝ), (1933447869 / 78125000000 : ℝ), (966194222759 / 100000000000000 : ℝ), G30D11M2.B⟩
noncomputable def m3 : Member := ⟨(1933447869 / 78125000000 : ℝ), (51530358547 / 2000000000000 : ℝ), (915341895249 / 100000000000000 : ℝ), G30D11M3.B⟩
noncomputable def m4 : Member := ⟨(51530358547 / 2000000000000 : ℝ), (13899636187 / 500000000000 : ℝ), (813637240219 / 100000000000000 : ℝ), G30D11M4.B⟩
noncomputable def m5 : Member := ⟨(13899636187 / 500000000000 : ℝ), (339015516757 / 10000000000000 : ℝ), (610227930169 / 100000000000000 : ℝ), G30D11M5.B⟩
theorem ok0 : m0.OK (1 / 10 ^ 70) (1 / 10 ^ 16) where
  ylo0 := by norm_num [m0, G30D11M0.B, errLo, errHi, Elo, Ehi]
  le := by norm_num [m0, G30D11M0.B, errLo, errHi, Elo, Ehi]
  yhi := by norm_num [m0, G30D11M0.B, errLo, errHi, Elo, Ehi]
  ahi0 := by norm_num [m0, G30D11M0.B, errLo, errHi, Elo, Ehi]
  ahi := by norm_num [m0, G30D11M0.B, errLo, errHi, Elo, Ehi]
  eLoH := by norm_num [m0, G30D11M0.B, errLo, errHi, Elo, Ehi]
  eLoA := by norm_num [m0, G30D11M0.B, errLo, errHi, Elo, Ehi]
  eHi := by norm_num [m0, G30D11M0.B, errLo, errHi, Elo, Ehi]
  pos1 := by norm_num [m0, G30D11M0.B, errLo, errHi, Elo, Ehi]
  hhi := by norm_num [m0, G30D11M0.B, errLo, errHi, Elo, Ehi]
  hlo := by norm_num [m0, G30D11M0.B, errLo, errHi, Elo, Ehi]
  amax := by norm_num [m0, G30D11M0.B, errLo, errHi, Elo, Ehi]
  amax1 := by norm_num [m0, G30D11M0.B, errLo, errHi, Elo, Ehi]
  slo := by norm_num [m0, G30D11M0.B, errLo, errHi, Elo, Ehi]
  hnlo := by norm_num [m0, G30D11M0.B, errLo, errHi, Elo, Ehi]
  elo := by norm_num [m0, G30D11M0.B, errLo, errHi, Elo, Ehi]
theorem adv0 : m0.AdvOK (3 / 10 : ℝ) (lam0 Config.spec) 0 0 :=
  Or.inr ⟨by norm_num, by unfold lam0; norm_num [m0, Config.spec]⟩
theorem ok1 : m1.OK (1 / 10 ^ 70) (1 / 10 ^ 16) where
  ylo0 := by norm_num [m1, G30D11M1.B, errLo, errHi, Elo, Ehi]
  le := by norm_num [m1, G30D11M1.B, errLo, errHi, Elo, Ehi]
  yhi := by norm_num [m1, G30D11M1.B, errLo, errHi, Elo, Ehi]
  ahi0 := by norm_num [m1, G30D11M1.B, errLo, errHi, Elo, Ehi]
  ahi := by norm_num [m1, G30D11M1.B, errLo, errHi, Elo, Ehi]
  eLoH := by norm_num [m1, G30D11M1.B, errLo, errHi, Elo, Ehi]
  eLoA := by norm_num [m1, G30D11M1.B, errLo, errHi, Elo, Ehi]
  eHi := by norm_num [m1, G30D11M1.B, errLo, errHi, Elo, Ehi]
  pos1 := by norm_num [m1, G30D11M1.B, errLo, errHi, Elo, Ehi]
  hhi := by norm_num [m1, G30D11M1.B, errLo, errHi, Elo, Ehi]
  hlo := by norm_num [m1, G30D11M1.B, errLo, errHi, Elo, Ehi]
  amax := by norm_num [m1, G30D11M1.B, errLo, errHi, Elo, Ehi]
  amax1 := by norm_num [m1, G30D11M1.B, errLo, errHi, Elo, Ehi]
  slo := by norm_num [m1, G30D11M1.B, errLo, errHi, Elo, Ehi]
  hnlo := by norm_num [m1, G30D11M1.B, errLo, errHi, Elo, Ehi]
  elo := by norm_num [m1, G30D11M1.B, errLo, errHi, Elo, Ehi]
theorem adv1 : m1.AdvOK (3 / 10 : ℝ) (lam0 Config.spec) 0 0 :=
  Or.inr ⟨by norm_num, by unfold lam0; norm_num [m1, Config.spec]⟩
theorem ok2 : m2.OK (1 / 10 ^ 70) (1 / 10 ^ 16) where
  ylo0 := by norm_num [m2, G30D11M2.B, errLo, errHi, Elo, Ehi]
  le := by norm_num [m2, G30D11M2.B, errLo, errHi, Elo, Ehi]
  yhi := by norm_num [m2, G30D11M2.B, errLo, errHi, Elo, Ehi]
  ahi0 := by norm_num [m2, G30D11M2.B, errLo, errHi, Elo, Ehi]
  ahi := by norm_num [m2, G30D11M2.B, errLo, errHi, Elo, Ehi]
  eLoH := by norm_num [m2, G30D11M2.B, errLo, errHi, Elo, Ehi]
  eLoA := by norm_num [m2, G30D11M2.B, errLo, errHi, Elo, Ehi]
  eHi := by norm_num [m2, G30D11M2.B, errLo, errHi, Elo, Ehi]
  pos1 := by norm_num [m2, G30D11M2.B, errLo, errHi, Elo, Ehi]
  hhi := by norm_num [m2, G30D11M2.B, errLo, errHi, Elo, Ehi]
  hlo := by norm_num [m2, G30D11M2.B, errLo, errHi, Elo, Ehi]
  amax := by norm_num [m2, G30D11M2.B, errLo, errHi, Elo, Ehi]
  amax1 := by norm_num [m2, G30D11M2.B, errLo, errHi, Elo, Ehi]
  slo := by norm_num [m2, G30D11M2.B, errLo, errHi, Elo, Ehi]
  hnlo := by norm_num [m2, G30D11M2.B, errLo, errHi, Elo, Ehi]
  elo := by norm_num [m2, G30D11M2.B, errLo, errHi, Elo, Ehi]
theorem adv2 : m2.AdvOK (3 / 10 : ℝ) (lam0 Config.spec) 0 0 :=
  Or.inr ⟨by norm_num, by unfold lam0; norm_num [m2, Config.spec]⟩
theorem ok3 : m3.OK (1 / 10 ^ 70) (1 / 10 ^ 16) where
  ylo0 := by norm_num [m3, G30D11M3.B, errLo, errHi, Elo, Ehi]
  le := by norm_num [m3, G30D11M3.B, errLo, errHi, Elo, Ehi]
  yhi := by norm_num [m3, G30D11M3.B, errLo, errHi, Elo, Ehi]
  ahi0 := by norm_num [m3, G30D11M3.B, errLo, errHi, Elo, Ehi]
  ahi := by norm_num [m3, G30D11M3.B, errLo, errHi, Elo, Ehi]
  eLoH := by norm_num [m3, G30D11M3.B, errLo, errHi, Elo, Ehi]
  eLoA := by norm_num [m3, G30D11M3.B, errLo, errHi, Elo, Ehi]
  eHi := by norm_num [m3, G30D11M3.B, errLo, errHi, Elo, Ehi]
  pos1 := by norm_num [m3, G30D11M3.B, errLo, errHi, Elo, Ehi]
  hhi := by norm_num [m3, G30D11M3.B, errLo, errHi, Elo, Ehi]
  hlo := by norm_num [m3, G30D11M3.B, errLo, errHi, Elo, Ehi]
  amax := by norm_num [m3, G30D11M3.B, errLo, errHi, Elo, Ehi]
  amax1 := by norm_num [m3, G30D11M3.B, errLo, errHi, Elo, Ehi]
  slo := by norm_num [m3, G30D11M3.B, errLo, errHi, Elo, Ehi]
  hnlo := by norm_num [m3, G30D11M3.B, errLo, errHi, Elo, Ehi]
  elo := by norm_num [m3, G30D11M3.B, errLo, errHi, Elo, Ehi]
theorem adv3 : m3.AdvOK (3 / 10 : ℝ) (lam0 Config.spec) 0 0 :=
  Or.inr ⟨by norm_num, by unfold lam0; norm_num [m3, Config.spec]⟩
theorem ok4 : m4.OK (1 / 10 ^ 70) (1 / 10 ^ 16) where
  ylo0 := by norm_num [m4, G30D11M4.B, errLo, errHi, Elo, Ehi]
  le := by norm_num [m4, G30D11M4.B, errLo, errHi, Elo, Ehi]
  yhi := by norm_num [m4, G30D11M4.B, errLo, errHi, Elo, Ehi]
  ahi0 := by norm_num [m4, G30D11M4.B, errLo, errHi, Elo, Ehi]
  ahi := by norm_num [m4, G30D11M4.B, errLo, errHi, Elo, Ehi]
  eLoH := by norm_num [m4, G30D11M4.B, errLo, errHi, Elo, Ehi]
  eLoA := by norm_num [m4, G30D11M4.B, errLo, errHi, Elo, Ehi]
  eHi := by norm_num [m4, G30D11M4.B, errLo, errHi, Elo, Ehi]
  pos1 := by norm_num [m4, G30D11M4.B, errLo, errHi, Elo, Ehi]
  hhi := by norm_num [m4, G30D11M4.B, errLo, errHi, Elo, Ehi]
  hlo := by norm_num [m4, G30D11M4.B, errLo, errHi, Elo, Ehi]
  amax := by norm_num [m4, G30D11M4.B, errLo, errHi, Elo, Ehi]
  amax1 := by norm_num [m4, G30D11M4.B, errLo, errHi, Elo, Ehi]
  slo := by norm_num [m4, G30D11M4.B, errLo, errHi, Elo, Ehi]
  hnlo := by norm_num [m4, G30D11M4.B, errLo, errHi, Elo, Ehi]
  elo := by norm_num [m4, G30D11M4.B, errLo, errHi, Elo, Ehi]
theorem adv4 : m4.AdvOK (3 / 10 : ℝ) (lam0 Config.spec) 0 0 :=
  Or.inr ⟨by norm_num, by unfold lam0; norm_num [m4, Config.spec]⟩
theorem ok5 : m5.OK (1 / 10 ^ 70) (1 / 10 ^ 16) where
  ylo0 := by norm_num [m5, G30D11M5.B, errLo, errHi, Elo, Ehi]
  le := by norm_num [m5, G30D11M5.B, errLo, errHi, Elo, Ehi]
  yhi := by norm_num [m5, G30D11M5.B, errLo, errHi, Elo, Ehi]
  ahi0 := by norm_num [m5, G30D11M5.B, errLo, errHi, Elo, Ehi]
  ahi := by norm_num [m5, G30D11M5.B, errLo, errHi, Elo, Ehi]
  eLoH := by norm_num [m5, G30D11M5.B, errLo, errHi, Elo, Ehi]
  eLoA := by norm_num [m5, G30D11M5.B, errLo, errHi, Elo, Ehi]
  eHi := by norm_num [m5, G30D11M5.B, errLo, errHi, Elo, Ehi]
  pos1 := by norm_num [m5, G30D11M5.B, errLo, errHi, Elo, Ehi]
  hhi := by norm_num [m5, G30D11M5.B, errLo, errHi, Elo, Ehi]
  hlo := by norm_num [m5, G30D11M5.B, errLo, errHi, Elo, Ehi]
  amax := by norm_num [m5, G30D11M5.B, errLo, errHi, Elo, Ehi]
  amax1 := by norm_num [m5, G30D11M5.B, errLo, errHi, Elo, Ehi]
  slo := by norm_num [m5, G30D11M5.B, errLo, errHi, Elo, Ehi]
  hnlo := by norm_num [m5, G30D11M5.B, errLo, errHi, Elo, Ehi]
  elo := by norm_num [m5, G30D11M5.B, errLo, errHi, Elo, Ehi]
theorem adv5 : m5.AdvOK (3 / 10 : ℝ) (lam0 Config.spec) 0 0 :=
  Or.inr ⟨by norm_num, by unfold lam0; norm_num [m5, Config.spec]⟩
theorem chain : Chained m0 [m1, m2, m3, m4, m5] := ⟨by norm_num [m0, m1], ⟨by norm_num [m1, m2], ⟨by norm_num [m2, m3], ⟨by norm_num [m3, m4], ⟨by norm_num [m4, m5], trivial⟩⟩⟩⟩⟩
theorem lot : LotConsts Config.spec (1 / 10 ^ 70) where
  p_pos := by norm_num [Config.spec]
  t0_pos := by norm_num [Config.spec]
  t1_le := by norm_num [Config.spec]
  a1_le := by unfold lam0; norm_num [Config.spec]
  a1_near := by unfold lam0; rw [abs_le]; constructor <;> norm_num [Config.spec]

theorem lo : m0.ylo ≤ (1 - (3 / 10 : ℝ)) * lam0 Config.spec := by unfold lam0; norm_num [m0, Config.spec]

theorem hi : lam0 Config.spec ≤ ((m0 :: [m1, m2, m3, m4, m5]).getLast (List.cons_ne_nil _ _)).yhi := by
  unfold lam0; norm_num [m5, Config.spec]

theorem small {E : Env} (hc : E.c = Config.spec) {L : List Note} (hD1 : 1 ≤ (es0 E).D)
    (hD : (es0 E).D ≤ 2 ^ 100) (hL : stakeOf L ≤ (es0 E).D) : Small E.c (es0 E) L (1 / 10 ^ 16) where
  D_pos := hD1
  D_le := by rw [hc]; norm_num [Config.spec]; omega
  S_small := by
    rw [hc]
    have h1 : (stakeOf L : ℝ) ≤ 2 ^ 100 := by exact_mod_cast le_trans hL hD
    have h0 : (0 : ℝ) ≤ stakeOf L := by positivity
    have hp : (0 : ℝ) < (Config.spec.p : ℝ) := by norm_num [Config.spec]
    have e1 : (stakeOf L : ℝ) / Config.spec.p ≤ 2 ^ 100 / Config.spec.p := div_le_div_of_nonneg_right h1 hp.le
    have e2 : (stakeOf L : ℝ) ^ 2 / Config.spec.p ≤ (2 ^ 100) ^ 2 / Config.spec.p :=
      div_le_div_of_nonneg_right (pow_le_pow_left₀ h0 h1 2) hp.le
    have e3 : (2 : ℝ) ^ 100 / Config.spec.p + (2 ^ 100) ^ 2 / Config.spec.p ≤ 1 / 10 ^ 16 := by
      norm_num [Config.spec]
    linarith

/-- **Certified finality in the first epoch, from stake fractions.** f = 1/30,
k = 2160, Δ = 11 slots. Random-oracle tickets, fresh lotteries (no grinding),
Δ-delivery; every honest node online throughout the first epoch; the adversary
holds at most `0.3` of the genesis stake, and all genesis stake is held by honest
nodes or the adversary (`H + A = D`). Then a finality violation within the first
643000 slots has probability at most `10^-10`. -/
theorem certified {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsProbabilityMeasure μ] {O : Ω → Oracle} (E : Env) (hc : E.c = Config.spec) (hΔ : E.Δ = 11)
    (hA : Assm E) (es : Ω → List Event) (hNF : ∀ ω, (wF (E.withO (O ω)) (es ω)).now ≤ 643000)
    (hdel : ∀ ω, DeltaDelivery (E.withO (O ω)) (es ω)) (hO : RandomOracle μ O E.c.p)
    (hσm : ∀ i, Measurable fun ω => σE (E.withO (O ω)) (es ω) i)
    (hfresh : Fresh μ O fun ω => σE (E.withO (O ω)) (es ω))
    (hon : ∀ j ∈ E.nodes, ∀ i < E.c.epochLength, E.online j i = true)
    (hs : ((es0 E).lead.map Note.id).Nodup) (hD1 : 1 ≤ (es0 E).D) (hD : (es0 E).D ≤ 2 ^ 100)
    (hfrac : (1 - (3 / 10 : ℝ)) * (stakeOf (advNotes (es0 E)) : ℝ) ≤ (3 / 10 : ℝ) * stakeOf (honNotes E 0 (es0 E) E.nodes))
    (hall : stakeOf (honNotes E 0 (es0 E) E.nodes) + stakeOf (advNotes (es0 E)) = (es0 E).D) :
    μ {ω | Unsafe (E.withO (O ω)) (es ω)} ≤ ENNReal.ofReal (1 / 10 ^ 10) := by
  have hEL : 0 < E.c.epochLength := by rw [hc]; norm_num [Config.spec, Config.epochLength, Config.kf]
  have hlot : LotConsts E.c (1 / 10 ^ 70) := hc ▸ lot
  obtain ⟨m, hm, hsb⟩ := genesis_member hlot (by norm_num) hA.nodup (by norm_num) hEL hon hs
    (small hc hD1 hD (by omega)) (small hc hD1 hD (by omega)) (by norm_num) (by norm_num) hfrac hall chain
    (by rw [hc]; exact lo) (by rw [hc]; exact hi)
    (by intro m hm; simp only [List.mem_cons, List.mem_singleton, List.not_mem_nil, or_false] at hm
        rcases hm with rfl | rfl | rfl | rfl | rfl | rfl
        · exact ok0
        · exact ok1
        · exact ok2
        · exact ok3
        · exact ok4
        · exact ok5
        )
    (by intro m hm; simp only [List.mem_cons, List.mem_singleton, List.not_mem_nil, or_false] at hm
        rw [hc]
        rcases hm with rfl | rfl | rfl | rfl | rfl | rfl
        · exact adv0
        · exact adv1
        · exact adv2
        · exact adv3
        · exact adv4
        · exact adv5
        )
  simp only [List.mem_cons, List.mem_singleton, List.not_mem_nil, or_false] at hm
  rcases hm with rfl | rfl | rfl | rfl | rfl | rfl
  · exact (G30D11M0.certified E hc hΔ hA es hNF hdel hO hσm hfresh hsb).trans
      (ENNReal.ofReal_le_ofReal (by norm_num))
  · exact (G30D11M1.certified E hc hΔ hA es hNF hdel hO hσm hfresh hsb).trans
      (ENNReal.ofReal_le_ofReal (by norm_num))
  · exact (G30D11M2.certified E hc hΔ hA es hNF hdel hO hσm hfresh hsb).trans
      (ENNReal.ofReal_le_ofReal (by norm_num))
  · exact (G30D11M3.certified E hc hΔ hA es hNF hdel hO hσm hfresh hsb).trans
      (ENNReal.ofReal_le_ofReal (by norm_num))
  · exact (G30D11M4.certified E hc hΔ hA es hNF hdel hO hσm hfresh hsb).trans
      (ENNReal.ofReal_le_ofReal (by norm_num))
  · exact (G30D11M5.certified E hc hΔ hA es hNF hdel hO hσm hfresh hsb).trans
      (ENNReal.ofReal_le_ofReal (by norm_num))

end Cryptarchia.Prob.Certs.G30D11
