"""First-epoch (genesis) certificates: one Cert2 per member of a band family along
Y_H + Y_A = λ (all genesis stake participating, adversary <= beta), and the combined theorem."""
import sys, json, math
from fractions import Fraction as Fr
from certnum import rup, rdn, flog10
from gen import lean_q as q
import plan
from emit2 import emit

P_SPEC = 0x30644E72E131A029B85045B68181585D2833E84879B9709143E1F593F0000001
T0 = 0x1a3fb997fd5838f2a1585ee090a95c88129ab25cc4d2e2d28f1a95f81d85465
LAM = Fr(T0, P_SPEC)
ETA, ZETA = Fr(1, 10 ** 70), Fr(1, 10 ** 16)

def errLo(Y): return 2 * (ETA * Y ** 2 + ZETA)
def errHi(Y): return 2 * (Fr(2, 9) * Y ** 3 + ETA * Y ** 2 + ZETA)
def Elo(y): return 1 - y + y * y / 2 - Fr(2, 9) * y ** 3
def Ehi(y): return 1 - y + y * y / 2

def member_band(ylo, yhi, ahi, d=13):
    P0lo = Elo(yhi) * (1 - errLo(yhi)); P0hi = Ehi(ylo) * (1 + 2 * errHi(yhi))
    amax = rup(1 - Elo(ahi) * (1 - errLo(ahi)), d)
    hhi = rup(1 - P0lo, d); hlo = rdn(1 - P0hi, d)
    return dict(hhi=hhi, hlo=hlo, amax=amax, alo=amax, hahi=rup(hhi * amax, d), halo=rdn(hlo * amax, d),
                slo=rdn(P0lo * (ylo - errHi(yhi)) * (1 - amax), d), hnlo=rdn(hlo * (1 - amax), d),
                elo=rdn(P0lo * (1 - amax), d))

def members(beta, fracs):
    """fracs: honest-exponent breakpoints as fractions of λ, first = 1 - beta, last = 1"""
    ys = [rdn(LAM * Fr(fracs[0]), 12)] + [rdn(LAM * Fr(f), 12) for f in fracs[1:-1]] + [rup(LAM, 12)]
    out = []
    for k in range(len(ys) - 1):
        ylo, yhi = ys[k], ys[k + 1]
        ahi = rup(LAM - ylo, 12)
        out.append(dict(ylo=ylo, yhi=yhi, ahi=ahi, B=member_band(ylo, yhi, ahi)))
    return out

def gen_member(beta, D, m, name, out_dir, N):
    Bf = {k: float(v) for k, v in m['B'].items()}
    plan.band = lambda f, b: Bf
    p = plan.plan(beta, D, N=N)
    def rnd(x, n): return Fr(round(x * 10 ** n), 10 ** n)
    c, z, s, k, d = p['par']
    c, z, s, d = rnd(c, 4), rnd(z, 4), max(Fr(1), rnd(s, 4)), min(Fr(1), rnd(d, 4))
    k = min(rnd(k, 4), z - s)
    cfg = dict(desc=f"f = 1/30, k = 2160, Δ = {D}, genesis member [{float(m['ylo']/LAM):.4f}λ, {float(m['yhi']/LAM):.4f}λ], adversary ≤ {float(m['ahi']/LAM):.4f}λ",
               fNum=1, fDen=30, beta=beta, Delta=D, k=2160, N=N, G=p['G'], Gp=p['Gp'], J=p['J'], Lw=p['Lw'], r=p['r'],
               T=p['T'], x=str(rnd(p['x'], 3)), yy=str(rnd(p['yy'], 2)), c=str(c), z=str(z), s=str(s), kap=str(k),
               d=str(d), tau=str(Fr(p['tau']).limit_denominator(1000)))
    assert N + max(cfg['G'], cfg['Gp']) + D + 2 < 648000
    for texp in range(int(-p['tot']) + 2, 0, -1):
        try:
            text, Ts, lp = emit(cfg, name, Fr(1, 10 ** texp), cfg['desc'], Bover=m['B'], mode='genesis')
            break
        except AssertionError:
            continue
    open(f"{out_dir}/{name}.lean", 'w').write(text)
    print(name, 'target 1e-%d' % texp, 'lp', float(lp), 'total', f"{float(sum(Ts)):.3e}", flush=True)
    return texp, cfg

if __name__ == "__main__":
    beta = float(sys.argv[1]); D = int(sys.argv[2]); idx = int(sys.argv[3]); out_dir = sys.argv[4]
    fracs = json.loads(sys.argv[5]); prefix = sys.argv[6]; N = int(sys.argv[7])
    ms = members(beta, fracs)
    texp, cfg = gen_member(beta, D, ms[idx], f"{prefix}M{idx}", out_dir, N)
    json.dump(dict(texp=texp, cfg=cfg), open(f"{prefix}M{idx}.json", "w"))

def emit_combined(beta, D, fracs, prefix, N, out_dir):
    ms = members(beta, fracs)
    K = len(ms)
    texps = [json.load(open(f"{prefix}M{k}.json"))['texp'] for k in range(K)]
    T = min(texps)
    bq = q(Fr(beta).limit_denominator(1000))
    L = []
    L.append("".join(f"import Cryptarchia.Prob.Certs.{prefix}.{prefix}M{k}\n" for k in range(K)))
    L.append(f"""
/-!
# First-epoch finality from stake fractions: β ≤ {beta}, Δ = {D}

Generated by `tools/certgen/emit_gen.py`. The genesis state's honest
exponent `λ·H/D` lies in one of {K} ranges covering `[(1-β)λ, λ]`; each range has
its own certificate (`{prefix}Mk.certified`). The worst is `10^-{T}`.
-/

namespace Cryptarchia.Prob.Certs.{prefix}

open Cryptarchia Cryptarchia.Prob

set_option maxRecDepth 100000
set_option maxHeartbeats 0
""")
    for k, m in enumerate(ms):
        L.append(f"noncomputable def m{k} : Member := ⟨{q(m['ylo'])}, {q(m['yhi'])}, {q(m['ahi'])}, {prefix}M{k}.B⟩\n")
    simps = "errLo, errHi, Elo, Ehi"
    fields = ['ylo0', 'le', 'yhi', 'ahi0', 'ahi', 'eLoH', 'eLoA', 'eHi', 'pos1', 'hhi', 'hlo', 'amax', 'amax1', 'slo', 'hnlo', 'elo']
    for k in range(K):
        L.append(f"theorem ok{k} : m{k}.OK (1 / 10 ^ 70) (1 / 10 ^ 16) where\n" +
                 "".join(f"  {f} := by norm_num [m{k}, {prefix}M{k}.B, {simps}]\n" for f in fields))
        L.append(f"theorem adv{k} : m{k}.AdvOK {bq} (lam0 Config.spec) 0 0 :=\n"
                 f"  Or.inr ⟨by norm_num, by unfold lam0; norm_num [m{k}, Config.spec]⟩\n")
    rest = ", ".join(f"m{k}" for k in range(1, K))
    chain = "⟨by norm_num [m0, m1], " + "".join(f"by norm_num [m{k}, m{k+1}], " for k in range(1, K - 1))
    # nested anonymous constructor: ⟨h01, ⟨h12, ... trivial⟩⟩
    def nest(k):
        if k == K - 1: return "trivial"
        return f"⟨by norm_num [m{k}, m{k+1}], {nest(k + 1)}⟩"
    L.append(f"theorem chain : Chained m0 [{rest}] := {nest(0)}\n")
    L.append(f"""theorem lot : LotConsts Config.spec (1 / 10 ^ 70) where
  p_pos := by norm_num [Config.spec]
  t0_pos := by norm_num [Config.spec]
  t1_le := by norm_num [Config.spec]
  a1_le := by unfold lam0; norm_num [Config.spec]
  a1_near := by unfold lam0; rw [abs_le]; constructor <;> norm_num [Config.spec]

theorem lo : m0.ylo ≤ (1 - {bq}) * lam0 Config.spec := by unfold lam0; norm_num [m0, Config.spec]

theorem hi : lam0 Config.spec ≤ ((m0 :: [{rest}]).getLast (List.cons_ne_nil _ _)).yhi := by
  unfold lam0; norm_num [m{K-1}, Config.spec]

theorem small {{E : Env}} (hc : E.c = Config.spec) {{L : List Note}} (hD1 : 1 ≤ (es0 E).D)
    (hD : (es0 E).D ≤ 2 ^ 100) (hL : stakeOf L ≤ (es0 E).D) : Small E.c (es0 E) L (1 / 10 ^ 16) where
  D_pos := hD1
  D_le := by rw [hc]; norm_num [Config.spec]; omega
  S_small := by
    rw [hc]
    have h1 : (stakeOf L : ℝ) ≤ 2 ^ 100 := by exact_mod_cast le_trans hL hD
    have h0 : (0 : ℝ) ≤ stakeOf L := by positivity
    have hp : (0 : ℝ) < (Config.spec.p : ℝ) := by norm_num [Config.spec]
    have e1 : (stakeOf L : ℝ) / Config.spec.p ≤ 2 ^ 100 / Config.spec.p := div_le_div_of_nonneg_right h1 hp.le
    have e2 : (stakeOf L : ℝ) ^ 2 / Config.spec.p ≤ (2 ^ 100) ^ 2 / Config.spec.p :=
      div_le_div_of_nonneg_right (pow_le_pow_left₀ h0 h1 2) hp.le
    have e3 : (2 : ℝ) ^ 100 / Config.spec.p + (2 ^ 100) ^ 2 / Config.spec.p ≤ 1 / 10 ^ 16 := by
      norm_num [Config.spec]
    linarith

/-- **Certified finality in the first epoch, from stake fractions.** f = 1/30,
k = 2160, Δ = {D} slots. Random-oracle tickets, fresh lotteries (no grinding),
Δ-delivery; every honest node online throughout the first epoch; the adversary
holds at most `{beta}` of the genesis stake, and all genesis stake is held by honest
nodes or the adversary (`H + A = D`). Then a finality violation within the first
{N} slots has probability at most `10^-{T}`. -/
theorem certified {{Ω : Type*}} [MeasurableSpace Ω] {{μ : MeasureTheory.Measure Ω}}
    [MeasureTheory.IsProbabilityMeasure μ] {{O : Ω → Oracle}} (E : Env) (hc : E.c = Config.spec) (hΔ : E.Δ = {D})
    (hA : Assm E) (es : Ω → List Event) (hNF : ∀ ω, (wF (E.withO (O ω)) (es ω)).now ≤ {N})
    (hdel : ∀ ω, DeltaDelivery (E.withO (O ω)) (es ω)) (hO : RandomOracle μ O E.c.p)
    (hσm : ∀ i, Measurable fun ω => σE (E.withO (O ω)) (es ω) i)
    (hfresh : Fresh μ O fun ω => σE (E.withO (O ω)) (es ω))
    (hon : ∀ j ∈ E.nodes, ∀ i < E.c.epochLength, E.online j i = true)
    (hs : ((es0 E).lead.map Note.id).Nodup) (hD1 : 1 ≤ (es0 E).D) (hD : (es0 E).D ≤ 2 ^ 100)
    (hfrac : (1 - {bq}) * (stakeOf (advNotes (es0 E)) : ℝ) ≤ {bq} * stakeOf (honNotes E 0 (es0 E) E.nodes))
    (hall : stakeOf (honNotes E 0 (es0 E) E.nodes) + stakeOf (advNotes (es0 E)) = (es0 E).D) :
    μ {{ω | Unsafe (E.withO (O ω)) (es ω)}} ≤ ENNReal.ofReal (1 / 10 ^ {T}) := by
  have hEL : 0 < E.c.epochLength := by rw [hc]; norm_num [Config.spec, Config.epochLength, Config.kf]
  have hlot : LotConsts E.c (1 / 10 ^ 70) := hc ▸ lot
  obtain ⟨m, hm, hsb⟩ := genesis_member hlot (by norm_num) hA.nodup (by norm_num) hEL hon hs
    (small hc hD1 hD (by omega)) (small hc hD1 hD (by omega)) (by norm_num) (by norm_num) hfrac hall chain
    (by rw [hc]; exact lo) (by rw [hc]; exact hi)
    (by intro m hm; simp only [List.mem_cons, List.mem_singleton, List.not_mem_nil, or_false] at hm
        rcases hm with {" | ".join("rfl" for _ in range(K))}
        {"".join(f"{'·' } exact ok{k}" + chr(10) + "        " for k in range(K))})
    (by intro m hm; simp only [List.mem_cons, List.mem_singleton, List.not_mem_nil, or_false] at hm
        rw [hc]
        rcases hm with {" | ".join("rfl" for _ in range(K))}
        {"".join(f"{'·' } exact adv{k}" + chr(10) + "        " for k in range(K))})
  simp only [List.mem_cons, List.mem_singleton, List.not_mem_nil, or_false] at hm
  rcases hm with {" | ".join("rfl" for _ in range(K))}
""")
    for k in range(K):
        L.append(f"""  · exact ({prefix}M{k}.certified E hc hΔ hA es hNF hdel hO hσm hfresh hsb).trans
      (ENNReal.ofReal_le_ofReal (by norm_num))
""")
    L.append(f"\nend Cryptarchia.Prob.Certs.{prefix}\n")
    open(f"{out_dir}/{prefix}.lean", "w").write("".join(L))
    print("combined target 1e-%d" % T)
