"""Emit a Lean certificate for final_bimm_prob2 (Cert2 + settleEps2)."""
import sys, json, math
from fractions import Fraction as F
from gen import lean_q, chain
from certnum import rup, rdn, flog10
from cert2 import band_exact, build, lp_exact, check_cert, xg_exact

def q(x): return lean_q(x)

def vdef(name, V, D):
    s = f"noncomputable def {name} : ℕ → Fin 3 → Bool → ℝ := fun q a u =>\n  match q, a.val, u with\n"
    for qq in range(D):
        for a in range(3):
            for u in (False, True):
                s += f"  | {qq}, {a}, {'true' if u else 'false'} => {q(V[(qq, a, u)])}\n"
    s += "  | _, _, _ => 0\n"
    return s

def epsilon(cfg, B, c, z, s, kap, d, tau, es, lp):
    """exact upper bound on settleEps2 through the same chains the Lean proof uses"""
    D, k, N = cfg['Delta'], cfg['k'], cfg['N']
    G, Gp, J, Lw, r, T = cfg['G'], cfg['Gp'], cfg['J'], cfg['Lw'], cfg['r'], cfg['T']
    x, yy = F(cfg['x']), F(cfg['yy'])
    lr, b = es[0], es[1]; stat = 1 + (b - 1) / (1 - lr)
    kf = k * cfg['fDen'] // cfg['fNum']; epl = 10 * kf; nonce = 6 * kf
    grow = epl - nonce - D - 3 - G; nbD = (grow + D) // (T + D); nEp = (N + 2) // epl
    out = {}
    base1 = rup(1 - (1 - B['hhi']) ** D, 14)
    out['long'] = chain(base1, G // D, True, name='la') + (base1,)
    base2 = rup(1 - B['hlo'], 14)
    out['empty'] = chain(base2, Gp, True, name='em') + (base2,)
    out['span_a'] = chain(es[17], J + 1, True, name='sa')
    out['span_b'] = chain(tau, Lw + 1, False, name='sb')
    out['fail'] = chain(lp, J, True, name='fa')
    base3 = 1 + (x - 1) * (1 - B['elo'])
    out['win_a'] = chain(base3, Lw, True, name='wa') + (base3,)
    out['win_b'] = chain(x, k + 1, False, name='wb')
    out['reach'] = chain(c, r + 1, False, name='rc')
    PT = 1 - (1 - B['hlo']) ** T
    base5 = rup(1 + (yy - 1) * PT, 14)
    out['grow_a'] = chain(base5, nbD, True, name='da') + (base5,)
    out['grow_b'] = chain(yy, k + r, False, name='db')
    U = lambda key: out[key][1]
    T1 = (N + 1) * U('long'); T2 = (N + 1) * U('empty'); T3 = (N + Gp + 1) * (U('span_a') / U('span_b'))
    T4 = (N + Gp + 1) * (U('fail') * es[2] * stat); T5 = (N + 1) * (U('win_a') / U('win_b'))
    T6 = (N + G + 1) * (stat / U('reach')); T7 = nEp * (U('grow_a') / U('grow_b'))
    Ts = [rup(t, 6) for t in (T1, T2, T3, T4, T5, T6, T7)]
    return out, Ts, dict(nbD=nbD, nEp=nEp, stat=stat)

def emit(cfg, name, target, desc, Bover=None, mode='ro'):
    D = cfg['Delta']; k = cfg['k']; N = cfg['N']
    G, Gp, J, Lw, r, T = cfg['G'], cfg['Gp'], cfg['J'], cfg['Lw'], cfg['r'], cfg['T']
    x, yy = F(cfg['x']), F(cfg['yy'])
    B = Bover if Bover is not None else band_exact(cfg['fNum'] / cfg['fDen'], cfg['beta'])
    c, z, s, kap, d, tau = (F(cfg[v]) for v in ['c', 'z', 's', 'kap', 'd', 'tau'])
    vs, es = build(B, D, c, z, s, kap, d, tau)
    lp = lp_exact(B, D, c, z, s, kap, d, es); lr, b = es[0], es[1]
    ok, oks = check_cert(B, D, c, z, s, kap, d, tau, lp, lr, b, es)
    assert ok, oks
    ch, Ts, aux = epsilon(cfg, B, c, z, s, kap, d, tau, es, lp)
    tot = sum(Ts)
    assert tot <= target, (float(tot), [float(t) for t in Ts])
    M = N + max(G, Gp) + D + 2
    nbD, nEp, stat = aux['nbD'], aux['nEp'], aux['stat']
    L = []
    L.append("import Cryptarchia.Prob.Cert\n")
    L.append(f"/-!\n# Certificate: {desc}\n\nGenerated by `tools/certgen/mkcfg.py`. Every number below is checked by `norm_num`.\n-/\n")
    L.append(f"namespace Cryptarchia.Prob.Certs.{name}\n\nopen Cryptarchia Cryptarchia.Prob\n")
    L.append("set_option maxRecDepth 100000\nset_option maxHeartbeats 0\n")
    L.append("/-- The band of per-slot probabilities. -/\nnoncomputable def B : Band where\n" +
             "".join(f"  {kk} := {q(B[kk])}\n" for kk in ['hhi', 'hlo', 'amax', 'hahi', 'slo', 'hnlo', 'elo', 'alo', 'halo']))
    C, Z, S, K, Dd, TAU = (q(v) for v in (c, z, s, kap, d, tau))
    args = f"{C} {Z} {S} {Dd} {TAU}"
    simps = "xgN, gtab, slot4, acap, B"
    for i in range(19):
        L.append(vdef(f"v{i}", vs[i], D))
        L.append(f"""theorem sol{i} : AutoSol B {D} (xg {args} {i}).1 (xg {args} {i}).2.1 (xg {args} {i}).2.2 v{i} := by
  rw [xg_{i}]
  constructor <;> intro q hq a u <;> interval_cases q <;> fin_cases a <;> cases u <;> norm_num [{simps}, v{i}]
""")
        L.append(f"""theorem he{i} : autoBound B (xg {args} {i}).1 (xg {args} {i}).2.1 (xg {args} {i}).2.2 v{i} ≤ {q(es[i])} := by
  rw [xg_{i}]
  norm_num [autoBound, {simps}, v{i}]
""")
    L.append("noncomputable def V : Fin 19 → ℕ → Fin 3 → Bool → ℝ := fun i =>\n  match i.val with\n" +
             "".join(f"  | {i} => v{i}\n" for i in range(18)) + "  | _ => v18\n")
    L.append("noncomputable def Ev : Fin 19 → ℝ := fun i =>\n  match i.val with\n" +
             "".join(f"  | {i} => {q(es[i])}\n" for i in range(18)) + f"  | _ => {q(es[18])}\n")
    e = [q(v) for v in es]; LP = q(lp)
    conds = {
        'he17': f"1 ≤ {e[17]}", 'hlr': f"{e[0]} ≤ {q(lr)}", 'hb': f"{e[1]} ≤ {q(b)}", 'w1': f"{e[0]} ≤ {LP}",
        'w0': f"{e[1]} - (1 - ({S} + {K}) * {Z}⁻¹) * (B.slo * B.elo ^ {D}) ≤ {LP}",
        'm1r0': f"{S} * ({e[3]} - {LP}) + {K} * ({e[7]} - {LP}) ≤ 0",
        'm1r1': f"{S} * {C} * ({e[4]} - {LP}) + {K} * {Dd} * ({e[8]} - {LP}) ≤ 0",
        'm1r2': f"{S} * {C} ^ 2 * ({e[4]} - {LP}) + {K} * {Dd} ^ 2 * ({e[9]} - {LP}) ≤ 0",
        'm1r3a': f"{e[4]} ≤ {LP}",
        'm1r3': f"{S} * {C} ^ 3 * ({e[4]} - {LP}) + {K} * {Dd} ^ 3 * max ({e[10]} - {LP}) 0 + {K} * {e[15]} ≤ 0",
        'm2r0': f"{S} * ({e[5]} - {LP}) + {K} * ({e[11]} - {LP}) ≤ 0",
        'm2r1': f"{S} * {C} * ({e[6]} - {LP}) + {K} * {Dd} * ({e[12]} - {LP}) ≤ 0",
        'm2r2': f"{S} * {C} ^ 2 * ({e[6]} - {LP}) + {K} * {Dd} ^ 2 * ({e[13]} - {LP}) ≤ 0",
        'm2r3a': f"{e[6]} ≤ {LP}",
        'm2r3': f"{S} * {C} ^ 3 * ({e[6]} - {LP}) + {K} * {Dd} ^ 3 * max ({e[14]} - {LP}) 0 + {K} * {e[16]} ≤ 0"}
    cl = "".join(f"  {kk} := by show {v}; norm_num [B]\n" for kk, v in conds.items())
    L.append(f"""/-- The cold certificate. -/
noncomputable def P : Cert2 B {D} where
  c := {C}
  z := {Z}
  s := {S}
  κ := {K}
  d := {Dd}
  τ := {TAU}
  lp := {LP}
  lr := {q(lr)}
  b := {q(b)}
  Bs := [B]
  weak := fun B' hB' => by simp only [List.mem_singleton] at hB'; subst hB'; exact Band.Weaker.refl _
  v := V
  e := Ev
  hc := by norm_num
  hz := by norm_num
  hs := by norm_num
  hκ := by norm_num
  hd0 := by norm_num
  hd1 := by norm_num
  hsz := by norm_num
  hτ := by norm_num
  hlp0 := by norm_num
  hlp := by norm_num
  hlr0 := by norm_num
  hlr1 := by norm_num
  hb1 := by norm_num
  helo := by norm_num [B]
  hΔ := by norm_num
  sol := by
    intro i B' hB'; simp only [List.mem_singleton] at hB'; subst hB'
    fin_cases i; exacts [{', '.join(f'sol{i}' for i in range(19))}]
  he := by
    intro i B' hB'; simp only [List.mem_singleton] at hB'; subst hB'
    fin_cases i; exacts [{', '.join(f'he{i}' for i in range(19))}]
{cl}""")
    # the numbers
    def lines(key): return "\n".join(ch[key][0])
    def hyp(key): return ch[key][2]
    def U(key): return q(ch[key][1])
    base1 = ch['long'][3]; base2 = ch['empty'][3]; base3 = ch['win_a'][3]; base5 = ch['grow_a'][3]
    STAT = f"(1 + ({q(b)} - 1) / (1 - {q(lr)}))"
    tgt = q(target)
    L.append(f"""/-- **The numbers.** -/
theorem eps_le (E : Env) (hc : E.c = Config.spec) :
    settleEps2 E B P {N} {G} {Gp} {J} {Lw} {r} {T} {q(x)} {q(yy)} ≤ {tgt} := by
  have hk : E.c.k = {k} := by rw [hc]; rfl
  have hnEp : nEp E {N} = {nEp} := by
    unfold nEp; rw [hc]; norm_num [Config.spec, Config.epochLength, Config.kf]
  have hnbD : nbD E {D} {G} {T} = {nbD} := by
    unfold nbD growLen; rw [hc]; norm_num [Config.spec, Config.epochLength, Config.kf, Config.nonceOffset, Config.s]
  have p17 : P.e 17 = {e[17]} := rfl
  have p2 : P.e 2 = {e[2]} := rfl
  have pτ : P.τ = {TAU} := rfl
  have plp : P.lp = {LP} := rfl
  have plr : P.lr = {q(lr)} := rfl
  have pb : P.b = {q(b)} := rfl
  have pc : P.c = {C} := rfl
  unfold settleEps2 PT
  rw [hk, hnEp, hnbD, p17, p2, pτ, plp, plr, pb, pc]
  simp only [B]
  -- long phases
{lines('long')}
  have e1 : (1 - (1 - {q(B['hhi'])}) ^ {D}) ^ ({G} / {D}) ≤ {U('long')} := by
    have hb : (0 : ℝ) ≤ 1 - (1 - {q(B['hhi'])}) ^ {D} := by norm_num
    have hb' : 1 - (1 - {q(B['hhi'])}) ^ {D} ≤ {q(base1)} := by norm_num
    rw [show ({G} / {D} : ℕ) = {G // D} by norm_num]
    exact (pow_le_pow_left₀ hb hb' _).trans {hyp('long')}
  -- long empty runs
{lines('empty')}
  have e2 : (1 - {q(B['hlo'])}) ^ {Gp} ≤ {U('empty')} := by
    have hb : (0 : ℝ) ≤ 1 - {q(B['hlo'])} := by norm_num
    have hb' : 1 - {q(B['hlo'])} ≤ {q(base2)} := by norm_num
    exact (pow_le_pow_left₀ hb hb' _).trans {hyp('empty')}
  -- long spans
{lines('span_a')}
{lines('span_b')}
  have e3 : {e[17]} ^ ({J} + 1) / {TAU} ^ ({Lw} + 1) ≤ {U('span_a')} / {U('span_b')} := by
    rw [show ({J} + 1 : ℕ) = {J + 1} by norm_num, show ({Lw} + 1 : ℕ) = {Lw + 1} by norm_num]
    exact div_le_div₀ (by norm_num) {hyp('span_a')} (by norm_num) {hyp('span_b')}
  -- failed checks
{lines('fail')}
  have e4 : {LP} ^ {J} * {e[2]} * {STAT} ≤ {U('fail')} * {e[2]} * {STAT} := by
    apply mul_le_mul_of_nonneg_right _ (by norm_num)
    exact mul_le_mul_of_nonneg_right {hyp('fail')} (by norm_num)
  -- crowded windows
{lines('win_a')}
{lines('win_b')}
  have e5 : (1 + ({q(x)} - 1) * (1 - {q(B['elo'])})) ^ {Lw} / {q(x)} ^ ({k} + 1) ≤ {U('win_a')} / {U('win_b')} := by
    rw [show (1 + ({q(x)} - 1) * (1 - {q(B['elo'])}) : ℝ) = {q(base3)} by norm_num,
      show ({k} + 1 : ℕ) = {k + 1} by norm_num]
    exact div_le_div₀ (by norm_num) {hyp('win_a')} (by norm_num) {hyp('win_b')}
  -- large reach
{lines('reach')}
  have e6 : {STAT} / {C} ^ ({r} + 1) ≤ {STAT} / {U('reach')} := by
    rw [show ({r} + 1 : ℕ) = {r + 1} by norm_num]
    exact div_le_div_of_nonneg_left (by norm_num) (by norm_num) {hyp('reach')}
  -- slow growth
{lines('grow_a')}
{lines('grow_b')}
  have e7 : (1 + ({q(yy)} - 1) * (if (1 : ℝ) ≤ {q(yy)} then 1 - (1 - {q(B['hhi'])}) ^ {T}
      else 1 - (1 - {q(B['hlo'])}) ^ {T})) ^ {nbD} / {q(yy)} ^ ({k} + {r}) ≤ {U('grow_a')} / {U('grow_b')} := by
    rw [if_neg (by norm_num), show ({k} + {r} : ℕ) = {k + r} by norm_num]
    have hb : (0 : ℝ) ≤ 1 + ({q(yy)} - 1) * (1 - (1 - {q(B['hlo'])}) ^ {T}) := by norm_num
    have hb' : 1 + ({q(yy)} - 1) * (1 - (1 - {q(B['hlo'])}) ^ {T}) ≤ {q(base5)} := by norm_num
    exact div_le_div₀ (by norm_num) ((pow_le_pow_left₀ hb hb' _).trans {hyp('grow_a')}) (by norm_num) {hyp('grow_b')}
  have f1 := mul_le_mul_of_nonneg_left e1 (by norm_num : (0 : ℝ) ≤ (({N} : ℕ) : ℝ) + 1)
  have f2 := mul_le_mul_of_nonneg_left e2 (by norm_num : (0 : ℝ) ≤ (({N} : ℕ) : ℝ) + 1)
  have f3 := mul_le_mul_of_nonneg_left e3 (by norm_num : (0 : ℝ) ≤ (({N} : ℕ) : ℝ) + (({Gp} : ℕ) : ℝ) + 1)
  have f4 := mul_le_mul_of_nonneg_left e4 (by norm_num : (0 : ℝ) ≤ (({N} : ℕ) : ℝ) + (({Gp} : ℕ) : ℝ) + 1)
  have f5 := mul_le_mul_of_nonneg_left e5 (by norm_num : (0 : ℝ) ≤ (({N} : ℕ) : ℝ) + 1)
  have f6 := mul_le_mul_of_nonneg_left e6 (by norm_num : (0 : ℝ) ≤ (({N} : ℕ) : ℝ) + (({G} : ℕ) : ℝ) + 1)
  have f7 := mul_le_mul_of_nonneg_left e7 (by norm_num : (0 : ℝ) ≤ (({nEp} : ℕ) : ℝ))
  refine le_trans (add_le_add (add_le_add (add_le_add (add_le_add (add_le_add (add_le_add f1 f2) f3) f4) f5) f6) f7) ?_
  norm_num
""")
    L.append(f"""/-- The band facts the worst-case kernel needs. -/
theorem hBp : B.Prod := ⟨by norm_num [B], by norm_num [B], by norm_num [B], by norm_num [B], by norm_num [B]⟩

/-- The certificate's family is its band. -/
theorem hBs : ∀ B' ∈ P.Bs, B'.Prod := fun B' hB' => by
  simp only [P, List.mem_singleton] at hB'; subst hB'; exact hBp
""")
    common_hyps = f"""{{Ω : Type*}} [MeasurableSpace Ω] {{μ : MeasureTheory.Measure Ω}}
    [MeasureTheory.IsProbabilityMeasure μ] {{O : Ω → Oracle}} (E : Env) (hc : E.c = Config.spec) (hΔ : E.Δ = {D})
    (hA : Assm E) (es : Ω → List Event) (hNF : ∀ ω, (wF (E.withO (O ω)) (es ω)).now ≤ {N})
    (hdel : ∀ ω, DeltaDelivery (E.withO (O ω)) (es ω)) (hO : RandomOracle μ O E.c.p)
    (hσm : ∀ i, Measurable fun ω => σE (E.withO (O ω)) (es ω) i)
    (hfresh : Fresh μ O fun ω => σE (E.withO (O ω)) (es ω))"""
    tail = f"""(G := {G}) (G' := {Gp}) (J := {J}) (Lw := {Lw})
    (r := {r}) (T := {T}) (x := {q(x)}) (yy := {q(yy)}) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num [B]) (by norm_num [B]) (by norm_num [B]) (by norm_num [B])).trans
    (ENNReal.ofReal_le_ofReal (eps_le E hc))"""
    if mode == 'ro':
        L.append(f"""/-- **Certified finality from a random oracle.** {desc}. The tickets are a random
oracle, each slot's tickets are fresh given the past and the slot's epoch state (no
grinding), honest blocks are delivered within Δ, and every epoch state a slot's
lottery runs under is within the band `B`. Then a finality violation has probability
at most `{target}`. -/
theorem certified {common_hyps}
    (hband : ∀ ω i, 1 ≤ i → i ≤ {M} → SlotBand B E i (σE (E.withO (O ω)) (es ω) i)) :
    μ {{ω | Unsafe (E.withO (O ω)) (es ω)}} ≤ ENNReal.ofReal {tgt} :=
  (final_bimm_ro (M := {M}) hA es hNF hdel hO hσm hfresh hΔ P hBs
    (fun ω i h1 h2 => ⟨B, List.mem_singleton_self B, hband ω i h1 h2⟩) {tail}
""")
    else:
        L.append(f"""/-- **Certified finality in the first epoch.** {desc}. Random-oracle tickets, fresh
lotteries, Δ-delivery, and the genesis state within the band `B` at every slot of
the first epoch. -/
theorem certified {common_hyps}
    (hgen : ∀ i < E.c.epochLength, SlotBand B E i (es0 E)) :
    μ {{ω | Unsafe (E.withO (O ω)) (es ω)}} ≤ ENNReal.ofReal {tgt} :=
  (final_bimm_ro (M := {M}) hA es hNF hdel hO hσm hfresh hΔ P hBs
    (fun ω i _ hi => ⟨B, List.mem_singleton_self B, by
      have hiE : i < E.c.epochLength := by
        rw [hc]; norm_num [Config.spec, Config.epochLength, Config.kf]; omega
      rw [σE_epoch0 _ _ (show i < (E.withO (O ω)).c.epochLength from hiE), es0_withO]
      exact hgen i hiE⟩) {tail}
""")
    L.append(f"end Cryptarchia.Prob.Certs.{name}\n")
    return "\n".join(L), Ts, lp

if __name__ == "__main__":
    cfg = json.loads(open(sys.argv[1]).read()); name = sys.argv[2]; out = sys.argv[3]
    target = F(cfg['target'])
    text, Ts, lp = emit(cfg, name, target, cfg['desc'])
    open(out, 'w').write(text)
    print('wrote', out, 'lp', float(lp), 'terms', [f"{float(t):.2e}" for t in Ts], 'total', f"{float(sum(Ts)):.3e}")
