import Cryptarchia.Prob.Certs.E20D11

/-!
# Cryptarchia certificates

A numeric instance of the settlement theorem at the specification's parameters,
generated by `tools/certgen`. Every number is checked by `norm_num`; building this
library takes about an hour (`lake build CryptarchiaCerts`).

* `E20D11` — every epoch for a year (49 epochs) at β = 0.2, Δ = 11 slots, k = 2160,
  with the stake estimate's concentration and full withholding (`final_bimm_ro_tsi3`).

Other configurations can be generated with `tools/certgen` (see its README).
-/
