import Cryptarchia.Prob.Certs.E20D11
import Cryptarchia.Prob.Certs.E20D11M2

/-!
# Cryptarchia certificates

Numeric instances of the settlement theorem at the specification's parameters,
generated by `tools/certgen`. Every number is checked by `norm_num`; building each
certificate takes about an hour (`lake build CryptarchiaCerts`).

* `E20D11` — every epoch for a year (49 epochs) at β = 0.2, Δ = 11 slots, k = 2160,
  with the stake estimate's concentration and full withholding (`final_bimm_ro_tsi3`).
* `E20D11M2` — the same parameters over two months (slot 5184000, 9 epochs), bounded
  by `1/10000000000`.

Other configurations can be generated with `tools/certgen` (see its README).
-/
