import Cryptarchia.Prob.Certs.B20D11
import Cryptarchia.Prob.Certs.B30D11
import Cryptarchia.Prob.Certs.B10D11
import Cryptarchia.Prob.Certs.B25D11
import Cryptarchia.Prob.Certs.B30D5
import Cryptarchia.Prob.Certs.B30D2
import Cryptarchia.Prob.Certs.G30D11
import Cryptarchia.Prob.Certs.E20D11
import Cryptarchia.Prob.Certs.E10D11

/-!
# Cryptarchia certificates

Numeric instances of the settlement theorems at the specification's parameters,
generated by `tools/certgen`. Every number is checked by `norm_num`; building this
library takes hours (`lake build CryptarchiaCerts`).

* `B*` — one epoch, a fixed band (`final_bimm_ro`).
* `G30D11` — the first epoch, from stake fractions at genesis.
* `E10D11`, `E20D11` — every epoch for a year, with the stake estimate's concentration
  (`final_bimm_ro_tsi3`).
-/
