/* The three-design comparison.
 *
 * Everything here is an exported MEASUREMENT (comparison.json, generated by
 * `empowering_denovo_sim.webexport`), not something the browser recomputes. Simulated
 * outcomes are not closed forms and pretending otherwise would be the one dishonest thing
 * this page could do.
 */
const D = await (await fetch("comparison.json")).json();
const state = { regime: "persistent" };

const pick = (design) => D.rows.find((r) => r.design === design && r.regime === state.regime);
const fmt = (x, d = 0) => x.toLocaleString("en-US", { maximumFractionDigits: d });

function row(tb, label, cur, dn, dns, note, marks = {}) {
  const tr = document.createElement("tr");
  const cell = (v, k) => {
    const m = marks[k];
    const cls = m === "ok" ? ' style="color:#1d7a5f;font-weight:700"'
      : m === "bad" ? ' style="color:#b3391a;font-weight:700"' : "";
    return `<td class="v"${cls}>${v}</td>`;
  };
  tr.innerHTML = `<td>${label}${note ? `<br><span class="n" style="font-size:.78rem">${note}</span>` : ""}</td>`
    + cell(cur, "cur") + cell(dn, "dn") + cell(dns, "dns");
  tb.appendChild(tr);
}

function renderTable() {
  const tb = document.getElementById("table");
  tb.innerHTML = "";
  const dn = pick("de novo"), dns = pick("de novo*");
  // Like for like: the current design measured at the SAME arrival rate and horizon as the
  // de-novo runs (130/epoch, 360 epochs), not at its own study's 100/400.
  const cur = state.regime === "retiring"
    ? D.current_design.elevated_retiring_at_denovo_rate
    : D.current_design.elevated_persistent_at_denovo_rate;
  const curDoor = state.regime === "retiring"
    ? D.current_design.door_closes_at_100_per_epoch_retiring
    : D.current_design.door_closes_at_100_per_epoch;

  row(tb, "nodes onboarded", fmt(cur), fmt(dn.bonds), fmt(dns.bonds),
      "reference parameters, this regime, all three at 130 arrivals/epoch over 360 epochs");
  row(tb, "a ×100 cohort's fate",
      `door shut`, `${(dn.spike_bonded * 100).toFixed(0)}% in`,
      `${(dns.spike_bonded * 100).toFixed(0)}% in`,
      "13,000 nodes arriving in one epoch (R5)",
      { cur: "bad", dn: "ok", dns: "ok" });
  row(tb, "its median wait to bond", "—", `${fmt(dn.spike_median_epochs)} epochs`,
      `${fmt(dns.spike_median_epochs)} epochs`, "the price de novo* pays");
  row(tb, "a 10× whale at its worst moment", "cannot happen",
      `${(dn.whale_capture * 100).toFixed(0)}% of the endowment`,
      `${(dns.whale_capture * 100).toFixed(0)}%`,
      "the current design's outflow is fixed, so it cannot be drained",
      { cur: "ok", dn: "bad", dns: "ok" });
  row(tb, "best adoption speed", "a hump — worst rate elevates ⅙ of the best",
      "none", "none", "does the mechanism care when people arrive?",
      { cur: "bad", dn: "ok", dns: "ok" });
  row(tb, "door closes at 100 arrivals/epoch",
      `epoch ${curDoor}`, "never", "never",
      "last cohort with even odds of getting in — strongly regime-dependent: epoch "
      + `${D.current_design.door_closes_at_100_per_epoch} under persistence, `
      + `${D.current_design.door_closes_at_100_per_epoch_retiring} under retirement`,
      { cur: "bad", dn: "ok", dns: "ok" });
  const curPnr = state.regime === "retiring"
    ? D.current_design.point_of_no_return_at_100_per_epoch_retiring
    : D.current_design.point_of_no_return_at_100_per_epoch;
  row(tb, "point of no return", `epoch ${curPnr}`,
      "none", "none",
      "queue exceeds every bond the pool can fund — epoch "
      + `${D.current_design.point_of_no_return_at_100_per_epoch} under persistence, `
      + `${D.current_design.point_of_no_return_at_100_per_epoch_retiring} under retirement`,
      { cur: "bad", dn: "ok", dns: "ok" });
  row(tb, "bootstrap ends", "never", `epoch ${dn.transition}`, `epoch ${dns.transition}`,
      "the pool is spent and the phase is over");
  row(tb, "parameters to defend", "3", "3", "4", "R1: fewer is better",
      { dns: "bad" });
}

// ---- charts -----------------------------------------------------------------------------
const INK2 = "#6a737d", LINE = "#e6e9ec";
const BLUE = "#2a78d6", ORANGE = "#eb6834", GREEN = "#1baf7a";

function frame(id, title, sub) {
  const cv = document.getElementById(id), dpr = window.devicePixelRatio || 1;
  const w = cv.clientWidth, h = cv.clientHeight;
  cv.width = w * dpr; cv.height = h * dpr;
  const g = cv.getContext("2d"); g.scale(dpr, dpr); g.clearRect(0, 0, w, h);
  g.font = "600 13px system-ui"; g.fillStyle = "#1b1f23"; g.fillText(title, 12, 19);
  if (sub) { g.font = "11px system-ui"; g.fillStyle = INK2; g.fillText(sub, 12, 34); }
  return [g, w, h];
}

function bars(id, title, sub, items, fmtVal, hiIsBad) {
  const [g, w, h] = frame(id, title, sub);
  const x0 = 130, y0 = 46, x1 = w - 60, y1 = h - 24;
  const max = Math.max(...items.map((i) => i.v), 1e-9);
  const bh = (y1 - y0) / items.length;
  items.forEach((it, k) => {
    const y = y0 + k * bh + bh * 0.2, hh = bh * 0.55;
    const ww = (x1 - x0) * (it.v / max);
    g.fillStyle = it.c; g.fillRect(x0, y, Math.max(ww, 2), hh);
    g.fillStyle = "#1b1f23"; g.font = "12px system-ui"; g.textAlign = "right";
    g.fillText(it.label, x0 - 8, y + hh * 0.75);
    g.textAlign = "left"; g.fillStyle = INK2;
    g.fillText(fmtVal(it.v), x0 + Math.max(ww, 2) + 6, y + hh * 0.75);
  });
  g.textAlign = "left";
}

function renderCharts() {
  const dn = pick("de novo"), dns = pick("de novo*");
  bars("whale", "what a 10× whale captures", "of the endowment, at its best moment",
       [{ label: "current", v: 0.0, c: GREEN },
        { label: "de novo", v: dn.whale_capture, c: ORANGE },
        { label: "de novo*", v: dns.whale_capture, c: BLUE }],
       (v) => v === 0 ? "cannot be drained" : `${(v * 100).toFixed(0)}%`);
  bars("cost", "what the bound costs the crowd", "×100 cohort's median wait to bond",
       [{ label: "de novo", v: dn.spike_median_epochs, c: ORANGE },
        { label: "de novo*", v: dns.spike_median_epochs, c: BLUE }],
       (v) => `${v.toFixed(0)} epochs — all still bond`);
}

function renderVerdict() {
  const dn = pick("de novo"), dns = pick("de novo*");
  const curDoor = state.regime === "retiring"
    ? D.current_design.door_closes_at_100_per_epoch_retiring
    : D.current_design.door_closes_at_100_per_epoch;
  document.getElementById("verdict").innerHTML = `
    <table><tbody>
      <tr><td style="width:9rem"><strong>current</strong></td><td class="n">
        Cannot be drained and cannot be rushed — but it rations a fixed flow, so it has a best
        adoption speed, a door that closes at epoch ${curDoor} in this regime, and a point of
        no return.</td></tr>
      <tr><td><strong>de novo</strong></td><td class="n">
        No best speed, no door, no point of no return — the budget follows the crowd. Pays for
        it by being drainable: ${(dn.whale_capture * 100).toFixed(0)}% of the endowment to one
        well-timed actor.</td></tr>
      <tr><td><strong>de novo*</strong></td><td class="n">
        The same, with the drain bounded to ${(dns.whale_capture * 100).toFixed(0)}% and flat in
        the whale's size. Costs one parameter with no natural value${
          dns.spike_median_epochs > dn.spike_median_epochs
            ? ` and makes the ×100 crowd wait ${((dns.spike_median_epochs / dn.spike_median_epochs - 1) * 100).toFixed(0)}% longer — all of it still bonds`
            : ` and, in this regime, nothing else: the ×100 crowd waits exactly as long with the bound as without it (${fmt(dns.spike_median_epochs)} epochs), and the same ${(dns.spike_bonded * 100).toFixed(0)}% of it bonds either way`
        }.</td></tr>
    </tbody></table>`;
}

function render() { renderTable(); renderCharts(); renderVerdict(); }

document.getElementById("regime").onchange = (e) => { state.regime = e.target.value; render(); };
document.getElementById("badge").textContent =
  `simulated outcomes exported from empowering_denovo_sim — ${D.rows.length} runs`;
document.getElementById("badge").className = "badge ok";
render();
window.addEventListener("resize", render);
